### ISSUE TITLE
Automations Tasks available for user contributions?

### ISSUE THREAD

**Issue by andy4222** [alfredapp/automation-tasks#1]
Hi @vitorgalvao , started using v5 EA and was looking into a few details about Automation Tasks. 

- Can we as users contribute to this repo?
- I noticed that the Tasks are JSON files with complex shell/bash script that execute the functionality. Any way we can use a different language and ref it from the JSON file?

**Comment by vitorgalvao** [comment]
> Can we as users contribute to this repo?

Yes. The contribution might be edited to conform to the style of the repo / fix bugs / add enhancements.

> shell/bash script that execute the functionality.

Most are in JXA, not shell. Others are in Zsh, as appropriate.

> Any way we can use a different language and ref it from the JSON file?

Technically you can use literally any language, just as you can with Workflows. Practically, not every language will be accepted in this repo if there’s an alternative way to do it. With Apple removing the language runtimes in macOS, those become dependencies. Automation Tasks should “just work” as often as possible, so the best languages to write them in right now are Bash / Zsh (latter preferred) and AppleScript / JXA (latter preferred). Swift will be a good contender too.

In the not too distant future a tool will be made available to make creating Automation Tasks easier, you won’t have to edit JSON files directly. I’m also working on a document with best practices to ensure consistency. There are still a bunch of Automation Tasks planned, so for now it’s best to suggest them rather than submit PRs. No harm in accompanying the suggestion with working code, if you already have it.
