### ISSUE TITLE
Some Automation Tasks for Safari break if no Safari Window open  

### ISSUE THREAD

**Issue by Hanspe-3019** [alfredapp/automation-tasks#9]
"Safari Tab List" or "Close Current Safari Tab" break when used against Safari with no window open. I suggest a reasonable output in these cases like empty list or empty string, so I do not have to make extra test before using such tasks.

`Task Error: ../.common/tabs: execution error: Error: TypeError: undefined is not an object (evaluating 'window.tabs') (-2700)`

**Comment by vitorgalvao** [comment]
What version of Automation Tasks are you on? See it under Alfred Preferences → Alfred Gallery → Automation Task Options…

**Comment by Hanspe-3019** [comment]
Alfred 5.1.4 and Automation Tasks 2023.7

**Comment by vitorgalvao** [comment]
Could you try again? Because I can’t reproduce your issue at all. Perhaps the tasks have updated since the last time you tried. Also, Safari has a few bugs where sometimes “phantom” windows and tabs are returned, so to be really sure quit Safari completely, then reopen it and try again.

If you can still reproduce the issue after that, please provide the smallest workflow you can make that reliably makes it happen for you so I can investigate further. I’ll also need your exact version of macOS.

**Comment by Hanspe-3019** [comment]
I'm sorry, I haven't described the situation sufficiently.

Using ScriptEditor with your snippet, there are three cases:

- Safari is not yet started: Your snippet starts Safari and Safari opens an untitled empty window.
- Safari is already started and there is at least one window (visible or minimized): Your snippet outputs the properties of  the active Safari window.
- Safari is still started, but all windows have been closed (Command-W). In this case, your snippet breaks with `Error -1719: Invalid index` because *.windows* is empty and *.windows[0]* does not exists.

I would prefer that the automation tasks intercept such a situation by testing *.windows().length* and then return an empty string or array.

macOS 13.6.3 (22G436)

**Comment by vitorgalvao** [comment]
You explained it well the first time. That’s exactly what I cannot reproduce because the Automation Task *does* consider that case. When that are no windows, an empty array is returned. That snippet errored exactly as it should. The point was to see if any of the “phantom” windows was around.

Try this:

```javascript
const windows = Application("Safari").windows()

const tabs = windows
  .flatMap(window => window.tabs())
  .filter(tab => tab !== null)
  .map(tab => [tab.url(), tab.name()])
	
tabs
```

What do you get?

**Comment by Hanspe-3019** [comment]
In the case where there are no windows, this snippet yields [], no suprise.

The decisive question is whether an automation tasks like "Current Safari Tab" actually execute this test. That doesn't seem to be the case.

```javascript
function run(argv) {
  const browser = argv[0] === "frontmost_browser" ?
    browserVariant(frontmostBrowserName()) :
    browserVariant(argv[0])
  const outFormat = argv[1]

  const currentTab = browser.variant === "webkit" ?
    browser.app.windows[0].currentTab :
    browser.app.windows[0].activeTab

  switch (outFormat) {
    /* snipp */
  }
}

```

**Comment by vitorgalvao** [comment]
Now we’re getting somewhere! I can reproduce, but this only happens in certain situations. E.g. if you use `Safari Tab List` (the one you first mentioned) with the default settings it returns `[]`, as per that snippet. But if it’s configured to only act on the frontmost window, or for any task that that acts on the frontmost tab, it’s reproducible.

I have the fix ready and it will be out in the next release. I’ll aim to get it out before the end of the year but I’m right now adding a new section so it will be out after that’s ready.

Thank you for the report.

**Comment by vitorgalvao** [comment]
New version released. Please update and it should work as you expect.
